version: '3'
services:
#  maven:
#    build: . #


  db:
    image: "mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "spotitube"
    volumes:
      - db-data:/foo

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db-data: