version: '3'
services:
  maven:
    build: . #


  db:
    image: "mysql"
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db-data:/foo

volumes:
  db-data: